### PR TITLE
Add min_size and max_size to file description

### PR DESCRIPTION
**Pull request by puredazzle**
Add info about the variables for min_size and max_size for acf_file. The value is entered in MB.

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks!

**Comment by fiskhandlarn** [comment]
@puredazzle Great stuff! Could the README.md benefit from having the same explanation as in your commit message ("The value is entered in MB.")? Either as comments in the example code or in the text above perhaps? 

Also, please note that 
> [The filesize may also be entered as a string containing the unit. eg. ’400 KB’](https://www.advancedcustomfields.com/resources/file/)

**Comment by vinkla** [comment]
@fiskhandlarn good idea! IMO we should add it as a comment within the snippet:

```php
4, // MB
```

**Comment by fiskhandlarn** [comment]
@vinkla I agree with writing it as a comment, but maybe something like this to convey both ways of writing file sizes:

```
'min_size' => '400 KB',
'max_size' => 5, // MB if entered as int
```

**Comment by puredazzle** [comment]
@vinkla @fiskhandlarn ok! added and pushed a new PR https://github.com/wordplate/acf/pull/20

**Pull request merged**
