### PR TITLE
TrueFalse labels on ui()

### PR DESCRIPTION
**Pull request by Grafikart**
I added two optional parameters to ui() to set up labels for on et off.

Thanks for this class, much easier to work with objects than array you have to memorize ;)

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request Jonathan!

Would it be possible if you were to add screenshots of the three UI button states to this pull request?

> Thanks for this class, much easier to work with objects than array you have to memorize ;)

I'm glad you like it  🙌

**Comment by Grafikart** [comment]
onLabel
onLabel

**Comment by vinkla** [comment]
Thanks! Maybe we should name the variables `$onText` and `$offText` to make it similar to the ACF backend. 

---
In a future version we should maybe rename the `->ui()` method to `->stylisedUi()`.

**Comment by Grafikart** [comment]
Do you want me to add the stylisedUi() in this PR ?

**Comment by vinkla** [comment]
> Do you want me to add the stylisedUi() in this PR ?

Thanks for the offer but let's wait with that change for now. If you feel up for it we would greatly appreciate a second pull request of course. I want to keep them separate since renaming the method is a breaking change.

**Comment by Grafikart** [comment]
Ok i'll do another commit (not renaming but adding the new method, deprecating the previous one, to avoid breaking change)

**Comment by vinkla** [comment]
Thanks Jonathan ✨

**Pull request merged**
