### PR TITLE
Fix property type in ConditionalLogic

### PR DESCRIPTION
**Pull request by szepeviktor**
Discovered by @phpstan

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request! In this case it should probably be `mixed` instead of `int`. Please update the pull request before we merge this.

**Comment by szepeviktor** [comment]
You're right.
Done.

**Comment by vinkla** [comment]
Thanks Viktor 🙌

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
